### ISSUE TITLE
Pulling from a private collection

### ISSUE THREAD

**Issue by ghost** [singularityhub/singularityhub.github.io#121]
I have a private collection with a singularity image I'd like to run with:

`singularity run -e -B INPUTS/:/INPUTS -B OUTPUTS/:/OUTPUTS shub://vuiiscci/Multi_Atlas_app`

However, since it's private (I assume) I'm getting:

```
singularity -vvv run -e -B INPUTS/:/INPUTS -B OUTPUTS/:/OUTPUTS shub://vuiiscci/Multi_Atlas_app
Increasing verbosity level (4)
Singularity version: 2.4.2-dist
Exec'ing: /usr/local/libexec/singularity/cli/run.exec
Evaluating args: '-e -B INPUTS/:/INPUTS -B OUTPUTS/:/OUTPUTS shub://vuiiscci/Multi_Atlas_app'
VERBOSE: Set messagelevel to: 4
VERBOSE: Initialize configuration file: /usr/local/etc/singularity/singularity.conf
VERBOSE: Got config key allow setuid = 'yes'
VERBOSE: Got config key max loop devices = '256'
VERBOSE: Got config key allow pid ns = 'yes'
VERBOSE: Got config key config passwd = 'yes'
VERBOSE: Got config key config group = 'yes'
VERBOSE: Got config key config resolv_conf = 'yes'
VERBOSE: Got config key mount proc = 'yes'
VERBOSE: Got config key mount sys = 'yes'
VERBOSE: Got config key mount dev = 'yes'
VERBOSE: Got config key mount devpts = 'yes'
VERBOSE: Got config key mount home = 'yes'
VERBOSE: Got config key mount tmp = 'yes'
VERBOSE: Got config key mount hostfs = 'no'
VERBOSE: Got config key bind path = '/etc/localtime'
VERBOSE: Got config key bind path = '/etc/hosts'
VERBOSE: Got config key user bind control = 'yes'
VERBOSE: Got config key enable overlay = 'try'
VERBOSE: Got config key mount slave = 'yes'
VERBOSE: Got config key sessiondir max size = '16'
VERBOSE: Got config key allow container squashfs = 'yes'
VERBOSE: Got config key allow container extfs = 'yes'
VERBOSE: Got config key allow container dir = 'yes'
VERBOSE: Got config key mksquashfs location = ''
VERBOSE: Got config key always use nv = 'no  '
VERBOSE: Got config key root default capabilities = 'no'
VERBOSE: Got config key allow root capabilities = 'yes'
VERBOSE: Got config key allow user capabilities = 'no'
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /home/local/VANDERBILT/blaberj/.singularity
VERBOSE2 REGISTRY not defined (None)
VERBOSE2 NAMESPACE not defined (None)
VERBOSE2 SINGULARITY_DOCKER_ARCHITECTURE found as amd64
VERBOSE2 SINGULARITY_DOCKER_OS found as linux
VERBOSE2 SINGULARITY_ENVIRONMENT found as None/.singularity.d/env/90-environment.sh
VERBOSE2 SINGULARITY_RUNSCRIPT found as None/singularity
VERBOSE2 SINGULARITY_TESTFILE found as None/.singularity.d/test
VERBOSE2 SINGULARITY_DEFFILE found as None/.singularity.d/Singularity
VERBOSE2 SINGULARITY_HELPFILE found as None/.singularity.d/runscript.help
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_NOHTTPS found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as .
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as /tmp/.singularity-layerfile.sLc11n
VERBOSE2 SINGULARITY_PYTHREADS found as 9
VERBOSE2 SINGULARITY_CONTAINER found as shub://vuiiscci/Multi_Atlas_app
VERBOSE2 SINGULARITY_PULLFOLDER found as .
Traceback (most recent call last):
  File "/usr/local/libexec/singularity/python/pull.py", line 74, in <module>
    main()
  File "/usr/local/libexec/singularity/python/pull.py", line 66, in main
    layerfile=LAYERFILE)
  File "/usr/local/libexec/singularity/python/shub/main.py", line 87, in PULL
    image_name = get_image_name(manifest)
  File "/usr/local/libexec/singularity/python/shub/api.py", line 242, in get_image_name
    return get_default_name(manifest)
  File "/usr/local/libexec/singularity/python/shub/api.py", line 252, in get_default_name
    if "tag" in manifest and "branch" in manifest:
TypeError: argument of type 'int' is not iterable
ABORT: Aborting with RETVAL=255
```
Is there a way we can log in (maybe by exporting environment variables) so I can pull this image?

Thanks,

-Justin

**Comment by vsoch** [comment]
You are actually only the second user to take advantage of private! What I added to the interface for this case is that you can click on the name of the image link to get a link to download your image from the browser. This is how the client does it, but getting the link from the manifest first. The reason private images aren't supported right now is because it would require a level of authentication beyond using Github as a third party, and there hasn't been enough need. If you badly need private images, then I suggest deployment of a Singularity Registry --> https://singularityhub.github.io/sregistry/ where you can host and push/pull to your heart's content!

**Comment by vsoch** [comment]
Closing issue as Singularity Hub is not intended typically to be providing these private images, and the user is suggested to contribute to Singularity Registry server.
